name: automate stage
on: 
  push:
    branches:
    - "features/**"  
env: 
  credentials: ${{ secrets.AZURE_OPT_NONPROD_CREDENTIALS }}
  registry_user: ${{ secrets.REGISTRY_AUT_USERNAME }}
  registry_pass: ${{ secrets.REGISTRY_AUT_PASSWORD }}
  git_ref: ${{ github.ref }}
  git_number: ${{ github.run_number }}
  git_sha: ${{ github.sha }}
jobs:    
  automate:
    runs-on: ubuntu-latest
    steps: 
      - name: Install dependencies
        shell: pwsh
        run: |
          Install-Module -Name Az -Repository PSGallery -Force
      - uses: actions/checkout@v2 
      - name: setup automate environment
        shell: pwsh
        run: |
          ./nonproduction/automate/build.ps1
      - run: |
          echo $FirstName




   

    