name: automate stage
on: 
  push:
    branches:
    - "features/**"  
env: 
  credentials: ${{ secrets.AZURE_OPT_NONPROD_CREDENTIALS }}
  registry_user: ${{ secrets.REGISTRY_AUT_USERNAME }}
  registry_pass: ${{ secrets.REGISTRY_AUT_PASSWORD }}  
  app_rg: 'mothership-aut-rg'
  app_location: 'eastus'
  
jobs:    
  automate:
    runs-on: ubuntu-latest
    steps: 
      - name: Install dependencies
        shell: pwsh
        run: |
          Install-Module -Name Az -Repository PSGallery -Force

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_OPT_NONPROD_CREDENTIALS}}   

      - uses: actions/checkout@v2 
      - uses: azure/docker-login@v1
        with:
          login-server: mothershipautregistry.azurecr.io
          username: ${{ secrets.REGISTRY_AUT_USERNAME }}
          password: ${{ secrets.REGISTRY_AUT_PASSWORD }}
      - run: |
          docker build -f "./AzureApp/Dockerfile" --force-rm . -t mothershipautregistry.azurecr.io/azureapp:${{ github.sha }}
          docker push mothershipautregistry.azurecr.io/azureapp:${{ github.sha }}
        working-directory: AzureApp             
      
      - run: |
          az account set --subscription "652129d9-5c47-49f8-ba58-0137a903edb0"
          az appservice plan create --name dev_${{ github.sha }} --resource-group 'mothership-aut-rg' --is-linux
          az webapp create --resource-group 'mothership-aut-rg' --plan dev_${{github.sha}} --name dev_${{ github.sha}} --deployment-container-image-name mothershipautregistry.azurecr.io/azureapp:${{ github.sha }}
          az webapp config appsettings set --resource-group 'mothership-aut-rg' --name dev_${{ github.sha}} --settings WEBSITES_PORT=8000