name: automate stage
on: 
  push:
    branches:
    - "features/**"  
env: 
  credentials: ${{ secrets.AZURE_OPT_NONPROD_CREDENTIALS }}
  registry_user: ${{ secrets.REGISTRY_AUT_USERNAME }}
  registry_pass: ${{ secrets.REGISTRY_AUT_PASSWORD }}
  app_rg: mothership-aut-rg
  app_location: eastus
  
jobs:    
  automate:
    runs-on: ubuntu-latest
    steps: 
      - name: Install dependencies
        shell: pwsh
        run: |
          Install-Module -Name Az -Repository PSGallery -Force

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}   
          
      - uses: actions/checkout@v2 
      - uses: azure/docker-login@v1
        with:
          login-server: mothershipautregistry.azurecr.io
          username: ${{ secrets.REGISTRY_AUT_USERNAME }}
          password: ${{ secrets.REGISTRY_AUT_PASSWORD }}
      - run: |
          docker build -f "./AzureApp/Dockerfile" --force-rm . -t mothershipautregistry.azurecr.io/azureapp:${{ github.ref }}-${{ github.run_number}}-${{ github.sha}}
          docker push mothershipautregistry.azurecr.io/azureapp:${{ github.ref }}-${{ github.run_number}}-${{ github.sha}}
        working-directory: AzureApp             
      
      - run: |
          az appservice plan create --name dev_${{github.sha}} --resource-group ${{app_rg}} --is-linux