name: automate stage
on: 
  push:
    branches:
    - "features/**"  
env: 
  credentials: ${{ secrets.AZURE_OPT_NONPROD_CREDENTIALS }}
  registry_user: ${{ secrets.AZURE_OPT_NONPROD_CREDENTIALS }}
  registry_pass: ${{ secrets.AZURE_OPT_NONPROD_CREDENTIALS }}
jobs:    
  automate:
    runs-on: ubuntu-latest
    steps: 
      - name: Install dependencies
        shell: pwsh
        run: |
          Install-Module -Name Az -Repository PSGallery -Force
      - uses: actions/checkout@v2 
      - name: setup automate environment
        shell: pwsh
        run: |
          ./nonproduction/automate/build.ps1

   

    