name: non-production pipeline
on: 
  push:
    paths:
    - "template"  
    - "nonproduction"
env: 
  credentials: ${{ secrets.AZURE_OPT_NONPROD_CREDENTIALS }}
jobs:    
  setup-automate:
    runs-on: ubuntu-latest
    steps: 
      - name: Install dependencies
        shell: pwsh
        run: |
          Install-Module -Name Az -Repository PSGallery -Force
      - uses: actions/checkout@v2 
      - name: setup automate
        shell: pwsh
        run: |
          ./nonproduction/automate/build.ps1
      - name: setup uat environment
        shell: pwsh
        run: |
          ./nonproduction/uat/build.ps1
      