name: production pipeline
on: 
  push:
    paths:
    - 'production/**'
env: # Or as an environment variable
  credentials: ${{ secrets.AZURE_OPT_PROD_CREDENTIALS }}
jobs:    
  setup-automate:
    runs-on: ubuntu-latest
    steps: 
      - name: Install dependencies
        shell: pwsh
        run: |
          Install-Module -Name Az -Repository PSGallery -Force
      - uses: actions/checkout@v2 
      - name: setup
        shell: pwsh
        run: |
          ./production/build.ps1
      


