name: automate stage
on: 
  push:
    branches:
    - "master/**"  
env: 
  credentials: ${{ secrets.AZURE_OPT_NONPROD_CREDENTIALS }}
jobs:    
  automate:
    runs-on: ubuntu-latest
    steps: 
      - name: Install dependencies
        shell: pwsh
        run: |
          Install-Module -Name Az -Repository PSGallery -Force
      - uses: actions/checkout@v2 

    